### ISSUE TITLE
Question about Motif Masking implementation

### ISSUE THREAD

**Issue by vincrichard** [einae-nd/MoAMa-dev#1]
Hello and thank you for your work on this paper. 
Could you point me where you are making the masking in the code ? 

I did found that the `MaskAtom` class seems to be responsible for the motif masking in the code, but the features in `data.x` does not seem to have been mask, so I think I am missing something.

Could you kindly explain where the masking takes place ? 

Best regards.

PS: There is an additional argument in this line:
https://github.com/einae-nd/MoAMa-dev/blob/626fed84e635a3671f08d5c2ae6eb7eeef923dc5/pretrain.py#L204
The code does not work with `graph_pooling` argument. I removed it for now, but maybe the code shared is not the final version ?

**Comment by einae-nd** [comment]
Thank you for your comments! The code for masking the `data.x` features were accidentally removed when cleaning the code for upload. The lines have been added back, so the masking should now be working as intended.

As for the missing argument, the GNN encoder does not perform any graph pooling, so the argument has been removed. This was another case of accidentally breaking the code when cleaning for upload.
