### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by Syzseisus** [einae-nd/MoAMa-dev#2]
Hello, thanks for your great work!
Where could I get datasets you used?
such as, [`datasets/zinc_standard_agent/raw`](https://github.com/einae-nd/MoAMa-dev/blob/626fed84e635a3671f08d5c2ae6eb7eeef923dc5/pretrain.py#L172)?

Sincerely, Syzseisus

**Comment by einae-nd** [comment]
Thank you for your question! Details on how to download the datasets are now included in the README.md file.

**Comment by Syzseisus** [comment]
Thanks a lot!
